datasources:
  default:
    dialect: MYSQL
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Pims@dm9
    schema-generate: CREATE_DROP
    url: jdbc:mysql://localhost:3306/db
    username: zenzhao
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
micronaut:
  application:
    name: micronautStarter
  caches:
    my-cache:
      maximumSize: 20
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
  session:
    http:
      cookie: true
      header: true

